### ISSUE TITLE
Can't "make" - also me noob in linux :)

### ISSUE THREAD

**Issue by eduard-fironda** [hanschen/ksuperkey#11]
`~/ksuperkey $ make
cc -Wall `pkg-config --cflags xtst x11` -o ksuperkey xcape.c `pkg-config --libs xtst x11` -pthread
xcape.c:22:20: fatal error: stdlib.h: No such file or directory
compilation terminated.
Makefile:14: recipe for target 'ksuperkey' failed
make: *** [ksuperkey] Error 1
~/ksuperkey $ 
`

**Comment by hanschen** [comment]
Which distribution do you use? It seems like your system is missing some standard C headers.

If you use something like Ubuntu or Mint, you could try the following:

    apt-get install build-essential

Then type `make` etc. again.

**Comment by eduard-fironda** [comment]
Mint 18 with kde plasma 5. If it was cinnamon i would not have a problem with the start button. Thank you for your response. I will try it tonight.

**Comment by wget** [comment]
@eduard-fironda And actually if you're all using the most up to date version of plasma (5.8), you won't need this project at all.

[Like specified in the README](https://github.com/hanschen/ksuperkey/blob/master/README.md), when the appplication menu has the chortcut `ALT+F1`, the latter is automatically mapped to the Windows key. However, please pay attention when using remote desktop tools like "Remote desktop (RDP)" or VNC, the superkey will be caught by the plasma environment and won't be forwarded to the remote desktop application.

**Comment by eduard-fironda** [comment]
It install with 5.6 and sudo apt-get update + upgrade doesn't update plasma and i don't know if it's stable to install it on my own

**Comment by wget** [comment]
@eduard-fironda No need to install/compile it by hand. On Ubuntu derivatives, there are PPA.

Simply type:
```
$ sudo add-apt-repository ppa:kubuntu-ppa/backports
$ sudo apt-get update
$ sudo apt-get dist-upgrade
```
and that should do the trick. ([sources](http://sourcedigit.com/21009-install-kde-plasma-5-8-on-ubuntu-16-04-and-linux-mint/))

Otherwise, like specified above, the compilation issues you have with ksuperkey are likely due to the build-essentials package which has not been installed, explaining why it could not find `stdlib.h` which is a standard from the C language.

**Comment by eduard-fironda** [comment]
Yeah .. just that i don't know if 5.8 it's stable ... 
As I saw .. 5.6 isn't stable so 5.8 is ? I will try with the build-essentials tonight and go for plasma 5.8 maybe later ...

**Comment by wget** [comment]
@eduard-fironda Can't say if 5.6 or 5.8 is stable on Mint. I'm an Arch Linux user, and since this is a rolling release distribution, we always have the latest versions of the pieces of software. On my side, plasma 5.8 is pretty stable. From my personal experience with Ubuntu and derivatives, kubuntu backports are pretty stable as well. I never had issues with them. (I was a Kubuntu user from Sep 2010 to Feb 2012).

**Comment by eduard-fironda** [comment]
Oh ... on Arch it's even more pain =)))) i have an Arch also on another system with plasma 5.1 or something. Dear God ... that was not stable at all =)))) but i did't use it for more than 6 months. Tried to change resolution (not in terminal) ... "Displays" was missing. Installed kscreen, and when opening "Displays" it said something about qt 5.7.0. Updated qt and then after restart ... plasma was not starting anymore. It get's stucked when it's checking the system.
Anyway this is offtopic, but thank you all for the answers.

**Comment by eduard-fironda** [comment]
Installed build essential and got a shorter problem now when "make" (and this is a freshly installed linux mint 18 with kde plasma 5.6.5)

`cc -Wall `pkg-config --cflags xtst x11` -o ksuperkey xcape.c `pkg-config --libs xtst x11` -pthread`

**Comment by wget** [comment]
@eduard-fironda It doesn't look like a problem, this is just a standard compilation line with the gnu gcc compiler linked against libs like the standard pthread lib.

**Comment by eduard-fironda** [comment]
I think it would have said more things. I did a "make" for a background a week ago and it was going and going in the terminal.

`ksuperkey: command not found`

**Comment by hanschen** [comment]
Try `./ksuperkey`

If you want to install ksuperkey system-wide, you can run `make install`, usually with root access through sudo:

    sudo make install

Then you can type `ksuperkey` to start the daemon. (Try it in a new terminal window.)

**Comment by eduard-fironda** [comment]
Well LOL. Forgot about sudo make install and in the readme it's missing. It works ! Thank you for the assistance

**Comment by hanschen** [comment]
Glad to hear that it's working :). The `make install` step is not necessary (and requires root access), you may as well run the binary `ksuperkey` directly from the directory (although most shells require you to type `./` in front, where `.` stands for the current directory, for security reasons). I will consider adding the make install part to the README though.

Closing this issue, feel free to re-open it if you have any other issues.
