### ISSUE TITLE
Usefull also on plasma 5.8

### ISSUE THREAD

**Issue by postadelmaga** [hanschen/ksuperkey#13]
Actually this small program is also useful on plasma 5.8.
I suggest to change the documentation to add the following use case

For example if you want to assign the super key to a different action than the ALT+F1 / run application launcher 

In my case I wanted to show desktop (Control + F12) with the super key, so remove the association ALT+F1 to the launcher and then  `ksuperkey -e 'Super_L=Control_L|F12'`

**Comment by hanschen** [comment]
True, I've updated the README to reflect this.

(It's possible to modify the Plasma config to run arbitrary dbus commands when Super is pressed and released, but it may not be as straightforward to change.)
