### ISSUE TITLE
ksuperkey only working when holding superkey down for a couple of seconds?

### ISSUE THREAD

**Issue by EkanshdeepGupta** [hanschen/ksuperkey#15]
Don't know how to troubleshoot this. Any advice welcome. Alt+F1 does open Launcher. And so does the super key, but only when I press it down for a couple of seconds. It used to work earlier. Recently I installed a whole bunch of updates, which also changed the skin and look of my launcher menu as well.

**Comment by hanschen** [comment]
Plasma 5.8 and above ships with this feature, so you don't have to use ksuperkey anymore. (If yhttps://github.com/hanschen/ksuperkey/issues/14ou wish to continue to use ksuperkey with the Super key, you should disable the Plasma mapping.)

See Issue #14 for more details.
