### ISSUE TITLE
Differences between ksuperkey and xcape

### ISSUE THREAD

**Issue by rauldipeas** [hanschen/ksuperkey#22]
I want to know whats the main differences between they.

**Comment by hanschen** [comment]
The main difference is the default binding. xcape binds Caps Lock to Ctrl and Escape by default, while ksuperkey binds the left Super/Windows key to Alt_L + F1.

This is for historic reasons - xcape used to not allow custom bindings, so I forked and adapted it for the purpose of opening the application launcher. Nowadays you could just use xcape for the same purpose. I've kept ksuperkey to both to not confuse existing users and to make it easier for new users.
