### ISSUE TITLE
Using different keyboard layout

### ISSUE THREAD

**Issue by Tcholly** [hanschen/ksuperkey#24]
In my keyboard settings, I have set alt+f1 as a shortcut for rofi. I also set the super key as alt+f1:
```
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &
```

Hoverver if i use alt+f1, i get rofi with the right keyboard layout (I use fr_CH, qwertz), but if I use the super key, I get a qwerty layout.

I use arch linux with xfce.

**Comment by hanschen** [comment]
Do you have any keyboard shortcuts for changing keyboard layout? And why do you run `ksuperkey` twice?

Can you see if you can reproduce the same issue with [xcape](https://github.com/alols/xcape)? If you can, it's probably an upstream issue.

**Comment by Tcholly** [comment]
I do not have any keyboard shortcuts for changing keyboard as I only use the qwertz layout, I don't know where it gets the qwerty layout.
Also I didn't notice you could use the `;` so I changed it now.
And yes I can reproduce the same error with xcape

**Comment by hanschen** [comment]
In that case I suggest that you report it to xcape, as `ksuperkey` is just a modified version of xcape with a different default keybind. Unfortunately the xcape repository doesn't seem to be active anymore, but maybe you can find a fork that's still maintained.

I'll close this issue as it's unlikely that I'll be able to fix it if it's not fixed upstream.
