### ISSUE TITLE
~12 second delay when no application in running

### ISSUE THREAD

**Issue by MehrunAskrnzhad** [hanschen/ksuperkey#25]
okay so I installed in on my laptop, I have dwm as window manager and sxhkd for keyboard shortcuts.
the problem is when I start the xorg server, in my xinitrc I start ksuperkey with just 'ksuperkey' and nothing passed to it. the ksuperkey is running, I press super key and it took around 12 seconds to generate the Alt_L + F1 keybinding, but when I open an application for example st terminal or qutebrowser or just anything, and the app is running and it's window is open, it takes less than 1 second, why is that hapening? is it just my problem?

update: I have same issue with xcape, what is going on? any helps?

**Comment by hanschen** [comment]
Unfortunately I don't know as I don't use dwm/sxhkd. As you have the same issue with xcape, I consider it an upstream bug - you could try reporting the issue there, but unfortunately I don't think xcape receives regular updates anymore.
