### ISSUE TITLE
ksuperkey suddenly not working in kde 4.14.2

### ISSUE THREAD

**Issue by adventurist** [hanschen/ksuperkey#9]
Worked great for many months and then suddenly isn't working.

Could you please provide some direction as to how one could go about troubleshooting?

**Comment by hanschen** [comment]
Did you update ksuperkey?

What happens when you try to assign a new shortcut (could be in any KDE application, for example the shortcut to show the application launcher) and press the Super key?

Can you make sure that only one process of ksuperkey is running?

**Comment by adventurist** [comment]
While trying to get it to work, I reinstalled it using "git clone https://github.com/hanschen/ksuperkey.git"

Should I try to assign a shortcut via 'System Settings'? Pardon me, I haven't yet tried remapping the keyboard in KDE.

System Activity is showing only one instance of ksuperkey. My autostart is setup with the following command: 

ksuperkey -e 'Super_L=Alt_L|F1'

**Comment by hanschen** [comment]
Does the application menu open if you press Alt+F1?

**Comment by adventurist** [comment]
It does not! And pressing Alt+F1 in terminal outputs "P"

**Comment by hanschen** [comment]
That's good, because then it's most likely not an issue with ksuperkey! :) You simply need to assign that key shortcut to show the application launcher.

If you don't know how to do that, you can follow [the guide I wrote here](http://blog.hanschen.org/2012/10/17/open-application-launcher-with-super-key/) (from step 2 under "How to make it work").

**Comment by adventurist** [comment]
Wonderful! Works perfectly now!
I wonder how that could have become unset...

Thank you so much for your prompt and helpful responses!

**Comment by hanschen** [comment]
No problem, glad that it worked out and thanks for closing the report.
